taskkill /IM DbxSvc.exe /f 
taskkill /IM Dropbox.exe /f 
taskkill /IM Explorer.exe /f 
rd /s /q "C:\Program Files (x86)\Dropbox\Client"
rd /s /q "C:\Program Files (x86)\Dropbox\"
rd /s /q "C:\ProgramData\Dropbox" 
rd /s /q "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Dropbox"
del "C:\Windows\System32\DbxSvc.exe"
rd /s /q "C:\Users\%~1\AppData\Local\Dropbox"
rd /s /q "C:\Users\%~1\AppData\Roaming\Dropbox"
call C:\Windows\explorer.exe
schtasks /delete /tn {1D6DDAC5-E292-4D54-B238-11F632E35B4E} /f
schtasks /delete  /tn {63A2405C-9B7B-422D-A25E-EE3B64D93ADB} /f
schtasks /delete /tn DropboxUpdateTaskMachineCore /f
schtasks /delete  /tn DropboxUpdateTaskMachineUA /f
REG DELETE HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FeatureUsage\AppSwitched /v {7C5A40EF-A0FB-4BFC-874A-C0F2E0B9FA8E}\Dropbox\Update\DropboxUpdate.exe /f /reg:32 
REG DELETE HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FeatureUsage\AppSwitched /v Dropbox.Desktop.Client /f /reg:32  
REG DELETE HKEY_CURRENT_USER\SOFTWARE\Dropbox /f /reg:32 	  
REG DELETE HKEY_CURRENT_USER\SOFTWARE\Dropbox	/v InfPatchComplete /f /reg:32  
REG DELETE HKEY_CURRENT_USER\SOFTWARE\Dropbox\ks /f /reg:32 	 
REG DELETE HKEY_CURRENT_USER\SOFTWARE\Dropbox\ks	/v Client-p /f /reg:32  
REG DELETE HKEY_CURRENT_USER\SOFTWARE\Dropbox\ks1 /f /reg:32 	 
REG DELETE HKEY_CURRENT_USER\SOFTWARE\Dropbox\ks1	/v Client-p /f /reg:32  
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314ED9-A251-47B7-93E1-CDD82E34AF8B} /f /reg:32 
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDA-A251-47B7-93E1-CDD82E34AF8B} /f /reg:32  
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDB-A251-47B7-93E1-CDD82E34AF8B} /f /reg:32  
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDC-A251-47B7-93E1-CDD82E34AF8B} /f /reg:32 
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDD-A251-47B7-93E1-CDD82E34AF8B} /f /reg:32 
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDE-A251-47B7-93E1-CDD82E34AF8B} /f /reg:32 
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDF-A251-47B7-93E1-CDD82E34AF8B} /f /reg:32 
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EE0-A251-47B7-93E1-CDD82E34AF8B} /f /reg:32 
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EE1-A251-47B7-93E1-CDD82E34AF8B} /f /reg:32 
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EE2-A251-47B7-93E1-CDD82E34AF8B} /f /reg:32 
REG DELETE HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\*\shellex\ContextMenuHandlers\DropboxExt	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\*\shellex\ContextMenuHandlers\DropboxExt	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.binder	 /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.binder	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.dbx-backup	/f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.dbx-backup	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.dbx-external-drive	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.dbx-external-drive	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.dbx-passwords /f /reg:32 	 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.dbx-passwords	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.dbx-vault	 /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.dbx-vault	 /ve /f /reg:32  

REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.gdoc\OpenWithProgids /v	Dropbox.Gdoc /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.gsheet\OpenWithProgids /v	Dropbox.Gsheet /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.gslides\OpenWithProgids /v	Dropbox.Gslides /f /reg:32 


REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.web\OpenWithProgids /v	Dropbox.Shortcut /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\InprocServer32	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\InprocServer32 /v	ThreadingModel /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\InprocServer32	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\ProgID	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\ProgID	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\Programmable /f /reg:32  	 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\TypeLib	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\TypeLib	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\Version	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\Version	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\VersionIndependentProgID	/f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\VersionIndependentProgID	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{E7A37920-253C-4FF1-B169-298A7CE6CAA9}	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{E7A37920-253C-4FF1-B169-298A7CE6CAA9}\LocalServer32	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{E7A37920-253C-4FF1-B169-298A7CE6CAA9}\LocalServer32	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{ECD97DE5-3C8F-4ACB-AEEE-CCAB78F7711C}	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{ECD97DE5-3C8F-4ACB-AEEE-CCAB78F7711C}\InprocServer32	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{ECD97DE5-3C8F-4ACB-AEEE-CCAB78F7711C}\InprocServer32 /v	ThreadingModel  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{ECD97DE5-3C8F-4ACB-AEEE-CCAB78F7711C}\InprocServer32	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{ECD97DE5-3C8F-4ACB-AEEE-CCAB78F7711C}\Programmable	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{ECD97DE5-3C8F-4ACB-AEEE-CCAB78F7711C}	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314ED9-A251-47B7-93E1-CDD82E34AF8B}	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314ED9-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314ED9-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32 /v	ThreadingModel /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314ED9-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314ED9-A251-47B7-93E1-CDD82E34AF8B}\Programmable	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314ED9-A251-47B7-93E1-CDD82E34AF8B}	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDA-A251-47B7-93E1-CDD82E34AF8B}	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDA-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDA-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32 /v	ThreadingModel /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDA-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDA-A251-47B7-93E1-CDD82E34AF8B}\Programmable	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDA-A251-47B7-93E1-CDD82E34AF8B}	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDB-A251-47B7-93E1-CDD82E34AF8B}	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDB-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDB-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32 /v	ThreadingModel /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDB-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDB-A251-47B7-93E1-CDD82E34AF8B}\Programmable	/f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDB-A251-47B7-93E1-CDD82E34AF8B}	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDC-A251-47B7-93E1-CDD82E34AF8B}	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDC-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDC-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32 /v	ThreadingModel /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDC-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDC-A251-47B7-93E1-CDD82E34AF8B}\Programmable	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDC-A251-47B7-93E1-CDD82E34AF8B}	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDD-A251-47B7-93E1-CDD82E34AF8B}	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDD-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDD-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32 /v	ThreadingModel /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDD-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDD-A251-47B7-93E1-CDD82E34AF8B}\Programmable	/f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDD-A251-47B7-93E1-CDD82E34AF8B}	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDE-A251-47B7-93E1-CDD82E34AF8B}	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDE-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDE-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32 /v	ThreadingModel /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDE-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDE-A251-47B7-93E1-CDD82E34AF8B}\Programmable	/f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDE-A251-47B7-93E1-CDD82E34AF8B}	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDF-A251-47B7-93E1-CDD82E34AF8B}	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDF-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDF-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32 /v	ThreadingModel /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDF-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDF-A251-47B7-93E1-CDD82E34AF8B}\Programmable	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDF-A251-47B7-93E1-CDD82E34AF8B}	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE0-A251-47B7-93E1-CDD82E34AF8B}	 /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE0-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE0-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32 /v	ThreadingModel /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE0-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE0-A251-47B7-93E1-CDD82E34AF8B}\Programmable	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE0-A251-47B7-93E1-CDD82E34AF8B}	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE1-A251-47B7-93E1-CDD82E34AF8B}	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE1-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE1-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32 /v	ThreadingModel /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE1-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE1-A251-47B7-93E1-CDD82E34AF8B}\Programmable	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE1-A251-47B7-93E1-CDD82E34AF8B}	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE2-A251-47B7-93E1-CDD82E34AF8B}	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE2-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	/f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE2-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32 /v	ThreadingModel /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE2-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE2-A251-47B7-93E1-CDD82E34AF8B}\Programmable	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE2-A251-47B7-93E1-CDD82E34AF8B}	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FBC9D74C-AF55-4309-9FB2-C426E071637F}	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FBC9D74C-AF55-4309-9FB2-C426E071637F}\InprocServer32	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FBC9D74C-AF55-4309-9FB2-C426E071637F}\InprocServer32 /v	ThreadingModel /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FBC9D74C-AF55-4309-9FB2-C426E071637F}\InprocServer32	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FBC9D74C-AF55-4309-9FB2-C426E071637F}\Programmable	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FBC9D74C-AF55-4309-9FB2-C426E071637F}	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\background\shellex\ContextMenuHandlers\DropboxExt	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\background\shellex\ContextMenuHandlers\DropboxExt	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\shellex\ContextMenuHandlers\DropboxExt	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\shellex\ContextMenuHandlers\DropboxExt	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\shellex\CopyHookHandlers\DropboxCopyHook	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\shellex\CopyHookHandlers\DropboxCopyHook	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Backup	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Backup\DefaultIcon	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Backup\DefaultIcon	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Backup\shell	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Backup\shell\Open	 /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Backup\shell\Open\Command	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Backup\shell\Open\Command	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Backup	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Binder	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Binder\DefaultIcon	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Binder\DefaultIcon	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Binder\shell	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Binder\shell\Open	 /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Binder\shell\Open\Command	 /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Binder\shell\Open\Command	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Binder	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.ExternalBackupLocation	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.ExternalBackupLocation\DefaultIcon	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.ExternalBackupLocation\DefaultIcon	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.ExternalBackupLocation\shell	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.ExternalBackupLocation\shell\Open	 /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.ExternalBackupLocation\shell\Open\Command	 /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.ExternalBackupLocation\shell\Open\Command	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.ExternalBackupLocation	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gdoc	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gdoc\DefaultIcon	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gdoc\DefaultIcon	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gdoc\shell	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gdoc\shell\Open	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gdoc\shell\Open\Command	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gdoc\shell\Open\Command	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gdoc	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gsheet	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gsheet\DefaultIcon	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gsheet\DefaultIcon	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gsheet\shell	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gsheet\shell\Open	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gsheet\shell\Open\Command /f /reg:32 	 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gsheet\shell\Open\Command	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gsheet	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gslides	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gslides\DefaultIcon	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gslides\DefaultIcon	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gslides\shell	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gslides\shell\Open	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gslides\shell\Open\Command	 /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gslides\shell\Open\Command	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gslides	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.OfficeAddIn	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.OfficeAddIn\CurVer	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.OfficeAddIn\CurVer	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.OfficeAddIn	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.OfficeAddIn.1	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.OfficeAddIn.1\CLSID	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.OfficeAddIn.1\CLSID	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.OfficeAddIn.1	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Paper	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Paper\DefaultIcon	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Paper\DefaultIcon	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Paper\shell	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Paper\shell\Open	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Paper\shell\Open\Command	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Paper\shell\Open\Command	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Paper	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.PaperT	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.PaperT\DefaultIcon	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.PaperT\DefaultIcon	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.PaperT\shell	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.PaperT\shell\Open	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.PaperT\shell\Open\Command	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.PaperT\shell\Open\Command	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.PaperT	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Passwords	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Passwords\DefaultIcon	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Passwords\DefaultIcon	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Passwords\shell	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Passwords\shell\Open	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Passwords\shell\Open\Command	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Passwords\shell\Open\Command	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Passwords	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Shortcut	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Shortcut\DefaultIcon	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Shortcut\DefaultIcon	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Shortcut\shell	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Shortcut\shell\Open	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Shortcut\shell\Open\Command	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Shortcut\shell\Open\Command	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Shortcut	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Vault	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Vault\DefaultIcon	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Vault\DefaultIcon	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Vault\shell	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Vault\shell\Open	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Vault\shell\Open\Command	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Vault\shell\Open\Command	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Vault	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client\DefaultIcon	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client\DefaultIcon	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client\shell	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client\shell\Open	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client\shell\Open\Command	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client\shell\Open\Command	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client\shell\Open	 /ve /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client\shell	 /ve /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client /v	URL Protocol /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-install	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-install\DefaultIcon	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-install\DefaultIcon	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-install\shell	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-install\shell\Open	  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-install\shell\Open\Command	 /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-install\shell\Open\Command	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-install\shell\Open	 /ve /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-install\shell	 /ve /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-install	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Interface\{3DD80E78-80D7-4E12-90CA-CBF68A68B1B3}	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Interface\{3DD80E78-80D7-4E12-90CA-CBF68A68B1B3}\ProxyStubClsid32	/f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Interface\{3DD80E78-80D7-4E12-90CA-CBF68A68B1B3}\ProxyStubClsid32	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Interface\{3DD80E78-80D7-4E12-90CA-CBF68A68B1B3}\TypeLib	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Interface\{3DD80E78-80D7-4E12-90CA-CBF68A68B1B3}\TypeLib /v	Version  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Interface\{3DD80E78-80D7-4E12-90CA-CBF68A68B1B3}\TypeLib	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Interface\{3DD80E78-80D7-4E12-90CA-CBF68A68B1B3}	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\lnkfile\shellex\ContextMenuHandlers\DropboxExt	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\lnkfile\shellex\ContextMenuHandlers\DropboxExt	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0\0	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0\0\win32	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0\0\win32	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0\0\win64	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0\0\win64	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0\FLAGS	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0\FLAGS	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0\HELPDIR	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0\HELPDIR	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0	 /ve /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Dropbox	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Dropbox\Client	 /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Dropbox\Client /v	Version  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Dropbox /v	InstallPath /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\DropboxUpdate /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\DropboxUpdate\Update\Clients\{CC46080E-4C33-4981-859A-BBA2F780F31E} /v	name /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run /v	Dropbox  /f /reg:32 
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314ED9-A251-47B7-93E1-CDD82E34AF8B} /f /reg:32 
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDA-A251-47B7-93E1-CDD82E34AF8B} /f /reg:32  
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDB-A251-47B7-93E1-CDD82E34AF8B} /f /reg:32 
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDC-A251-47B7-93E1-CDD82E34AF8B} /f /reg:32 
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDD-A251-47B7-93E1-CDD82E34AF8B} /f /reg:32 
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDE-A251-47B7-93E1-CDD82E34AF8B} /f /reg:32 
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDF-A251-47B7-93E1-CDD82E34AF8B} /f /reg:32 
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EE0-A251-47B7-93E1-CDD82E34AF8B} /f /reg:32 
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EE1-A251-47B7-93E1-CDD82E34AF8B} /f /reg:32 
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EE2-A251-47B7-93E1-CDD82E34AF8B} /f /reg:32 
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tasks\{1D6DDAC5-E292-4D54-B238-11F632E35B4E}" /f /reg:32 
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tasks\{63A2405C-9B7B-422D-A25E-EE3B64D93ADB}" /f /reg:32 
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tree\DropboxUpdateTaskMachineCore" /f /reg:32 
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tree\DropboxUpdateTaskMachineUA" /f /reg:32 
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox"	 /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	DisplayIcon /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	DisplayName /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	DisplayVersion /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	HelpLink  /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	InstallLocation /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	NoModify /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	NoRepair /f /reg:32  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	Publisher /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	UninstallPath /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	UninstallString /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	URLInfoAbout /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	VersionMajor /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	VersionMinor /f /reg:32 
REG DELETE HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\FirewallRules /v	{7A19E09C-5A68-424E-B585-62D982F96C2D} /f /reg:32 
REG DELETE HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FeatureUsage\AppSwitched /v {7C5A40EF-A0FB-4BFC-874A-C0F2E0B9FA8E}\Dropbox\Update\DropboxUpdate.exe /f /reg:64  
REG DELETE HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FeatureUsage\AppSwitched /v Dropbox.Desktop.Client /f /reg:64   
REG DELETE HKEY_CURRENT_USER\SOFTWARE\Dropbox /f /reg:64  	  
REG DELETE HKEY_CURRENT_USER\SOFTWARE\Dropbox	/v InfPatchComplete /f /reg:64   
REG DELETE HKEY_CURRENT_USER\SOFTWARE\Dropbox\ks /f /reg:64  	 
REG DELETE HKEY_CURRENT_USER\SOFTWARE\Dropbox\ks	/v Client-p /f /reg:64   
REG DELETE HKEY_CURRENT_USER\SOFTWARE\Dropbox\ks1 /f /reg:64  	 
REG DELETE HKEY_CURRENT_USER\SOFTWARE\Dropbox\ks1	/v Client-p /f /reg:64   
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314ED9-A251-47B7-93E1-CDD82E34AF8B} /f /reg:64  
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDA-A251-47B7-93E1-CDD82E34AF8B} /f /reg:64   
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDB-A251-47B7-93E1-CDD82E34AF8B} /f /reg:64   
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDC-A251-47B7-93E1-CDD82E34AF8B} /f /reg:64  
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDD-A251-47B7-93E1-CDD82E34AF8B} /f /reg:64  
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDE-A251-47B7-93E1-CDD82E34AF8B} /f /reg:64  
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDF-A251-47B7-93E1-CDD82E34AF8B} /f /reg:64  
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EE0-A251-47B7-93E1-CDD82E34AF8B} /f /reg:64  
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EE1-A251-47B7-93E1-CDD82E34AF8B} /f /reg:64  
REG DELETE "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EE2-A251-47B7-93E1-CDD82E34AF8B} /f /reg:64  
REG DELETE HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\*\shellex\ContextMenuHandlers\DropboxExt	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\*\shellex\ContextMenuHandlers\DropboxExt	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.binder	 /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.binder	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.dbx-backup	/f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.dbx-backup	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.dbx-external-drive	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.dbx-external-drive	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.dbx-passwords /f /reg:64  	 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.dbx-passwords	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.dbx-vault	 /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.dbx-vault	 /ve /f /reg:64   

REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.gdoc\OpenWithProgids /v	Dropbox.Gdoc /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.gsheet\OpenWithProgids /v	Dropbox.Gsheet /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.gslides\OpenWithProgids /v	Dropbox.Gslides /f /reg:64  


REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.web\OpenWithProgids /v	Dropbox.Shortcut /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\InprocServer32	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\InprocServer32 /v	ThreadingModel /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\InprocServer32	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\ProgID	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\ProgID	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\Programmable /f /reg:64   	 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\TypeLib	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\TypeLib	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\Version	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\Version	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\VersionIndependentProgID	/f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}\VersionIndependentProgID	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{CF142CA5-83C5-4E06-8FEA-310AA519A945}	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{E7A37920-253C-4FF1-B169-298A7CE6CAA9}	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{E7A37920-253C-4FF1-B169-298A7CE6CAA9}\LocalServer32	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{E7A37920-253C-4FF1-B169-298A7CE6CAA9}\LocalServer32	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{ECD97DE5-3C8F-4ACB-AEEE-CCAB78F7711C}	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{ECD97DE5-3C8F-4ACB-AEEE-CCAB78F7711C}\InprocServer32	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{ECD97DE5-3C8F-4ACB-AEEE-CCAB78F7711C}\InprocServer32 /v	ThreadingModel  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{ECD97DE5-3C8F-4ACB-AEEE-CCAB78F7711C}\InprocServer32	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{ECD97DE5-3C8F-4ACB-AEEE-CCAB78F7711C}\Programmable	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{ECD97DE5-3C8F-4ACB-AEEE-CCAB78F7711C}	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314ED9-A251-47B7-93E1-CDD82E34AF8B}	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314ED9-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314ED9-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32 /v	ThreadingModel /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314ED9-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314ED9-A251-47B7-93E1-CDD82E34AF8B}\Programmable	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314ED9-A251-47B7-93E1-CDD82E34AF8B}	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDA-A251-47B7-93E1-CDD82E34AF8B}	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDA-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDA-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32 /v	ThreadingModel /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDA-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDA-A251-47B7-93E1-CDD82E34AF8B}\Programmable	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDA-A251-47B7-93E1-CDD82E34AF8B}	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDB-A251-47B7-93E1-CDD82E34AF8B}	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDB-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDB-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32 /v	ThreadingModel /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDB-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDB-A251-47B7-93E1-CDD82E34AF8B}\Programmable	/f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDB-A251-47B7-93E1-CDD82E34AF8B}	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDC-A251-47B7-93E1-CDD82E34AF8B}	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDC-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDC-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32 /v	ThreadingModel /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDC-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDC-A251-47B7-93E1-CDD82E34AF8B}\Programmable	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDC-A251-47B7-93E1-CDD82E34AF8B}	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDD-A251-47B7-93E1-CDD82E34AF8B}	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDD-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDD-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32 /v	ThreadingModel /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDD-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDD-A251-47B7-93E1-CDD82E34AF8B}\Programmable	/f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDD-A251-47B7-93E1-CDD82E34AF8B}	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDE-A251-47B7-93E1-CDD82E34AF8B}	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDE-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDE-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32 /v	ThreadingModel /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDE-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDE-A251-47B7-93E1-CDD82E34AF8B}\Programmable	/f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDE-A251-47B7-93E1-CDD82E34AF8B}	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDF-A251-47B7-93E1-CDD82E34AF8B}	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDF-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDF-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32 /v	ThreadingModel /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDF-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDF-A251-47B7-93E1-CDD82E34AF8B}\Programmable	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EDF-A251-47B7-93E1-CDD82E34AF8B}	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE0-A251-47B7-93E1-CDD82E34AF8B}	 /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE0-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE0-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32 /v	ThreadingModel /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE0-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE0-A251-47B7-93E1-CDD82E34AF8B}\Programmable	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE0-A251-47B7-93E1-CDD82E34AF8B}	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE1-A251-47B7-93E1-CDD82E34AF8B}	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE1-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE1-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32 /v	ThreadingModel /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE1-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE1-A251-47B7-93E1-CDD82E34AF8B}\Programmable	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE1-A251-47B7-93E1-CDD82E34AF8B}	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE2-A251-47B7-93E1-CDD82E34AF8B}	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE2-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	/f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE2-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32 /v	ThreadingModel /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE2-A251-47B7-93E1-CDD82E34AF8B}\InprocServer32	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE2-A251-47B7-93E1-CDD82E34AF8B}\Programmable	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FB314EE2-A251-47B7-93E1-CDD82E34AF8B}	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FBC9D74C-AF55-4309-9FB2-C426E071637F}	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FBC9D74C-AF55-4309-9FB2-C426E071637F}\InprocServer32	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FBC9D74C-AF55-4309-9FB2-C426E071637F}\InprocServer32 /v	ThreadingModel /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FBC9D74C-AF55-4309-9FB2-C426E071637F}\InprocServer32	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FBC9D74C-AF55-4309-9FB2-C426E071637F}\Programmable	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{FBC9D74C-AF55-4309-9FB2-C426E071637F}	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\background\shellex\ContextMenuHandlers\DropboxExt	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\background\shellex\ContextMenuHandlers\DropboxExt	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\shellex\ContextMenuHandlers\DropboxExt	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\shellex\ContextMenuHandlers\DropboxExt	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\shellex\CopyHookHandlers\DropboxCopyHook	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\shellex\CopyHookHandlers\DropboxCopyHook	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Backup	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Backup\DefaultIcon	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Backup\DefaultIcon	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Backup\shell	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Backup\shell\Open	 /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Backup\shell\Open\Command	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Backup\shell\Open\Command	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Backup	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Binder	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Binder\DefaultIcon	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Binder\DefaultIcon	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Binder\shell	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Binder\shell\Open	 /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Binder\shell\Open\Command	 /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Binder\shell\Open\Command	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Binder	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.ExternalBackupLocation	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.ExternalBackupLocation\DefaultIcon	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.ExternalBackupLocation\DefaultIcon	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.ExternalBackupLocation\shell	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.ExternalBackupLocation\shell\Open	 /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.ExternalBackupLocation\shell\Open\Command	 /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.ExternalBackupLocation\shell\Open\Command	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.ExternalBackupLocation	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gdoc	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gdoc\DefaultIcon	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gdoc\DefaultIcon	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gdoc\shell	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gdoc\shell\Open	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gdoc\shell\Open\Command	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gdoc\shell\Open\Command	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gdoc	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gsheet	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gsheet\DefaultIcon	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gsheet\DefaultIcon	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gsheet\shell	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gsheet\shell\Open	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gsheet\shell\Open\Command /f /reg:64  	 
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gsheet\shell\Open\Command	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gsheet	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gslides	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gslides\DefaultIcon	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gslides\DefaultIcon	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gslides\shell	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gslides\shell\Open	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gslides\shell\Open\Command	 /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gslides\shell\Open\Command	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Gslides	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.OfficeAddIn	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.OfficeAddIn\CurVer	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.OfficeAddIn\CurVer	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.OfficeAddIn	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.OfficeAddIn.1	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.OfficeAddIn.1\CLSID	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.OfficeAddIn.1\CLSID	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.OfficeAddIn.1	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Paper	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Paper\DefaultIcon	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Paper\DefaultIcon	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Paper\shell	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Paper\shell\Open	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Paper\shell\Open\Command	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Paper\shell\Open\Command	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Paper	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.PaperT	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.PaperT\DefaultIcon	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.PaperT\DefaultIcon	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.PaperT\shell	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.PaperT\shell\Open	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.PaperT\shell\Open\Command	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.PaperT\shell\Open\Command	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.PaperT	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Passwords	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Passwords\DefaultIcon	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Passwords\DefaultIcon	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Passwords\shell	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Passwords\shell\Open	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Passwords\shell\Open\Command	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Passwords\shell\Open\Command	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Passwords	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Shortcut	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Shortcut\DefaultIcon	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Shortcut\DefaultIcon	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Shortcut\shell	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Shortcut\shell\Open	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Shortcut\shell\Open\Command	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Shortcut\shell\Open\Command	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Shortcut	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Vault	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Vault\DefaultIcon	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Vault\DefaultIcon	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Vault\shell	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Vault\shell\Open	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Vault\shell\Open\Command	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Vault\shell\Open\Command	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Dropbox.Vault	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client\DefaultIcon	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client\DefaultIcon	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client\shell	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client\shell\Open	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client\shell\Open\Command	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client\shell\Open\Command	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client\shell\Open	 /ve /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client\shell	 /ve /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client /v	URL Protocol /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-client	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-install	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-install\DefaultIcon	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-install\DefaultIcon	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-install\shell	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-install\shell\Open	  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-install\shell\Open\Command	 /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-install\shell\Open\Command	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-install\shell\Open	 /ve /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-install\shell	 /ve /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\dropbox-install	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Interface\{3DD80E78-80D7-4E12-90CA-CBF68A68B1B3}	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Interface\{3DD80E78-80D7-4E12-90CA-CBF68A68B1B3}\ProxyStubClsid32	/f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Interface\{3DD80E78-80D7-4E12-90CA-CBF68A68B1B3}\ProxyStubClsid32	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Interface\{3DD80E78-80D7-4E12-90CA-CBF68A68B1B3}\TypeLib	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Interface\{3DD80E78-80D7-4E12-90CA-CBF68A68B1B3}\TypeLib /v	Version  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Interface\{3DD80E78-80D7-4E12-90CA-CBF68A68B1B3}\TypeLib	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Interface\{3DD80E78-80D7-4E12-90CA-CBF68A68B1B3}	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\lnkfile\shellex\ContextMenuHandlers\DropboxExt	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\lnkfile\shellex\ContextMenuHandlers\DropboxExt	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0\0	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0\0\win32	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0\0\win32	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0\0\win64	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0\0\win64	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0\FLAGS	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0\FLAGS	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0\HELPDIR	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0\HELPDIR	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Classes\TypeLib\{527E621D-39D6-4627-8185-08F387A73307}\1.0	 /ve /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Dropbox	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Dropbox\Client	 /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Dropbox\Client /v	Version  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Dropbox /v	InstallPath /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\DropboxUpdate /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\DropboxUpdate\Update\Clients\{CC46080E-4C33-4981-859A-BBA2F780F31E} /v	name /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run /v	Dropbox  /f /reg:64  
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314ED9-A251-47B7-93E1-CDD82E34AF8B} /f /reg:64  
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDA-A251-47B7-93E1-CDD82E34AF8B} /f /reg:64   
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDB-A251-47B7-93E1-CDD82E34AF8B} /f /reg:64  
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDC-A251-47B7-93E1-CDD82E34AF8B} /f /reg:64  
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDD-A251-47B7-93E1-CDD82E34AF8B} /f /reg:64  
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDE-A251-47B7-93E1-CDD82E34AF8B} /f /reg:64  
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EDF-A251-47B7-93E1-CDD82E34AF8B} /f /reg:64  
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EE0-A251-47B7-93E1-CDD82E34AF8B} /f /reg:64  
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EE1-A251-47B7-93E1-CDD82E34AF8B} /f /reg:64  
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Approved" /v	{FB314EE2-A251-47B7-93E1-CDD82E34AF8B} /f /reg:64  
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tasks\{1D6DDAC5-E292-4D54-B238-11F632E35B4E}" /f /reg:64  
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tasks\{63A2405C-9B7B-422D-A25E-EE3B64D93ADB}" /f /reg:64  
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tree\DropboxUpdateTaskMachineCore" /f /reg:64  
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tree\DropboxUpdateTaskMachineUA" /f /reg:64  
REG DELETE "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox"	 /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	DisplayIcon /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	DisplayName /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	DisplayVersion /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	HelpLink  /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	InstallLocation /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	NoModify /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	NoRepair /f /reg:64   
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	Publisher /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	UninstallPath /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	UninstallString /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	URLInfoAbout /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	VersionMajor /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Dropbox /v	VersionMinor /f /reg:64  
REG DELETE HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\FirewallRules /v	{7A19E09C-5A68-424E-B585-62D982F96C2D} /f /reg:64  
pause